### ISSUE TITLE
Appearances

### ISSUE THREAD

**Issue by jeed2424** [opendocument-app/OpenDocument.ios#24]
The app looks exactly like "Files" and as much as I love Apple isn't the most user-friendly app... I was thinking of something more like the "Google Drive look"... Just a quick thought, will work on that!

**Comment by TomTasche** [comment]
Agreed, I went with the most standard way because it was the easiest to implement. I saw other apps that do similar things but look much nicer. I forgot which app it was unfortunately... Google Drive sounds good though

**Comment by jeed2424** [comment]
Completely understandable, I'd love to know which app(s) you thought looked nicer if you can remember!

**Comment by jeed2424** [comment]
Here's exactly what I was thinking we could do: 
![Screen Shot 2019-05-20 at 12 03 08 PM](https://user-images.githubusercontent.com/50756835/58035693-569ab100-7af7-11e9-8b0f-24d4ef7b8dec.png)

**Comment by TomTasche** [comment]
That seems like the "more logical" approach to a file explorer UI. However Apple being Apple, iOS bring iOS, I'm not sure which one actual users would prefer (I'm an Android user)? I'd assume that Apple did their homework and tune the standard UI to match iOS users' expectations.

**Comment by jeed2424** [comment]
Being an Apple and Android user (mostly Apple though), I know exactly what you mean. The difference between both is clear, but it doesn't have to be for an app... I was thinking of this type of design because that's the "standard" iOS approach (Apple definitely pushes it), a more conservative design that iOS users are familiar with (and it makes them say: "Sooo easy to use!", every time!).

**Comment by TomTasche** [comment]
Haha that sounds great! I'd love if users said that every time they open the app.

I'm planning to invest time and money into a redesign for iOS if the app turns out to be successful. Until then I don't think it makes sense to spend too much time on that (unless someone wants to do it for fun and experience of course).

At the moment we are lurking around the hundreds of downloads, so still a long way to go until success... 🙂
